<?xml version="1.0"?>
<package format="3">
  <name>robmovil_ekf</name>
  <version>0.1.0</version>
  <description>Trabajo final Robotica Movil.</description>
  <maintainer email="maxifisz@gmail.com">Maximiliano Fisz</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>

  <build_depend>robmovil_msgs</build_depend>
  <build_depend>nav_msgs</build_depend>
  <build_depend>laser</build_depend>
  <build_depend>kfilter</build_depend>
  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
